<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vip.proto

namespace Interact\VipInfo;

use UnexpectedValueException;

/**
 *Vip状态
 *
 * Protobuf type <code>interact.VipInfo.VipStatus</code>
 */
class VipStatus
{
    /**
     * 未指定
     *
     * Generated from protobuf enum <code>Unspecified = 0;</code>
     */
    const Unspecified = 0;
    /**
     *开启状态
     *
     * Generated from protobuf enum <code>On = 1;</code>
     */
    const On = 1;
    /**
     *关闭状态
     *
     * Generated from protobuf enum <code>Off = 2;</code>
     */
    const Off = 2;

    private static $valueToName = [
        self::Unspecified => 'Unspecified',
        self::On => 'On',
        self::Off => 'Off',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(VipStatus::class, \Interact\VipInfo_VipStatus::class);

