<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

namespace Interact;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *个人信息返回
 *
 * Generated from protobuf message <code>interact.AccountInfoResponse</code>
 */
class AccountInfoResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *余额
     *
     * Generated from protobuf field <code>float amount = 1;</code>
     */
    protected $amount = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $amount
     *          余额
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Account::initOnce();
        parent::__construct($data);
    }

    /**
     *余额
     *
     * Generated from protobuf field <code>float amount = 1;</code>
     * @return float
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     *余额
     *
     * Generated from protobuf field <code>float amount = 1;</code>
     * @param float $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkFloat($var);
        $this->amount = $var;

        return $this;
    }

}

