<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto

namespace Interact;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 创建新用户请求
 *
 * Generated from protobuf message <code>interact.AddAccountRequest</code>
 */
class AddAccountRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *用户权限token
     *
     * Generated from protobuf field <code>string token = 1;</code>
     */
    protected $token = '';
    /**
     *账号
     *
     * Generated from protobuf field <code>string account = 2;</code>
     */
    protected $account = '';
    /**
     *邮箱
     *
     * Generated from protobuf field <code>string email = 3;</code>
     */
    protected $email = '';
    /**
     *手机号
     *
     * Generated from protobuf field <code>string phone = 4;</code>
     */
    protected $phone = '';
    /**
     *昵称
     *
     * Generated from protobuf field <code>string name = 5;</code>
     */
    protected $name = '';
    /**
     *三级域名
     *
     * Generated from protobuf field <code>string url = 6;</code>
     */
    protected $url = '';
    /**
     *备注
     *
     * Generated from protobuf field <code>string memo = 7;</code>
     */
    protected $memo = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $token
     *          用户权限token
     *     @type string $account
     *          账号
     *     @type string $email
     *          邮箱
     *     @type string $phone
     *          手机号
     *     @type string $name
     *          昵称
     *     @type string $url
     *          三级域名
     *     @type string $memo
     *          备注
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Account::initOnce();
        parent::__construct($data);
    }

    /**
     *用户权限token
     *
     * Generated from protobuf field <code>string token = 1;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     *用户权限token
     *
     * Generated from protobuf field <code>string token = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    /**
     *账号
     *
     * Generated from protobuf field <code>string account = 2;</code>
     * @return string
     */
    public function getAccount()
    {
        return $this->account;
    }

    /**
     *账号
     *
     * Generated from protobuf field <code>string account = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAccount($var)
    {
        GPBUtil::checkString($var, True);
        $this->account = $var;

        return $this;
    }

    /**
     *邮箱
     *
     * Generated from protobuf field <code>string email = 3;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     *邮箱
     *
     * Generated from protobuf field <code>string email = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     *手机号
     *
     * Generated from protobuf field <code>string phone = 4;</code>
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     *手机号
     *
     * Generated from protobuf field <code>string phone = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone = $var;

        return $this;
    }

    /**
     *昵称
     *
     * Generated from protobuf field <code>string name = 5;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     *昵称
     *
     * Generated from protobuf field <code>string name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     *三级域名
     *
     * Generated from protobuf field <code>string url = 6;</code>
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     *三级域名
     *
     * Generated from protobuf field <code>string url = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->url = $var;

        return $this;
    }

    /**
     *备注
     *
     * Generated from protobuf field <code>string memo = 7;</code>
     * @return string
     */
    public function getMemo()
    {
        return $this->memo;
    }

    /**
     *备注
     *
     * Generated from protobuf field <code>string memo = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setMemo($var)
    {
        GPBUtil::checkString($var, True);
        $this->memo = $var;

        return $this;
    }

}

