<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vip.proto

namespace Interact;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *修改会员类型
 *
 * Generated from protobuf message <code>interact.EditVipRequest</code>
 */
class EditVipRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *LOGO
     *
     * Generated from protobuf field <code>optional string logo = 1;</code>
     */
    protected $logo = null;
    /**
     *名称
     *
     * Generated from protobuf field <code>optional string name = 2;</code>
     */
    protected $name = null;
    /**
     *价格
     *
     * Generated from protobuf field <code>optional float price = 3;</code>
     */
    protected $price = null;
    /**
     *简介
     *
     * Generated from protobuf field <code>optional string msg = 4;</code>
     */
    protected $msg = null;
    /**
     *vip标识
     *
     * Generated from protobuf field <code>int32 mark = 5;</code>
     */
    protected $mark = 0;
    /**
     *token
     *
     * Generated from protobuf field <code>string token = 6;</code>
     */
    protected $token = '';
    /**
     *原价
     *
     * Generated from protobuf field <code>float original_price = 7;</code>
     */
    protected $original_price = 0.0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $logo
     *          LOGO
     *     @type string $name
     *          名称
     *     @type float $price
     *          价格
     *     @type string $msg
     *          简介
     *     @type int $mark
     *          vip标识
     *     @type string $token
     *          token
     *     @type float $original_price
     *          原价
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Vip::initOnce();
        parent::__construct($data);
    }

    /**
     *LOGO
     *
     * Generated from protobuf field <code>optional string logo = 1;</code>
     * @return string
     */
    public function getLogo()
    {
        return isset($this->logo) ? $this->logo : '';
    }

    public function hasLogo()
    {
        return isset($this->logo);
    }

    public function clearLogo()
    {
        unset($this->logo);
    }

    /**
     *LOGO
     *
     * Generated from protobuf field <code>optional string logo = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLogo($var)
    {
        GPBUtil::checkString($var, True);
        $this->logo = $var;

        return $this;
    }

    /**
     *名称
     *
     * Generated from protobuf field <code>optional string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return isset($this->name) ? $this->name : '';
    }

    public function hasName()
    {
        return isset($this->name);
    }

    public function clearName()
    {
        unset($this->name);
    }

    /**
     *名称
     *
     * Generated from protobuf field <code>optional string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     *价格
     *
     * Generated from protobuf field <code>optional float price = 3;</code>
     * @return float
     */
    public function getPrice()
    {
        return isset($this->price) ? $this->price : 0.0;
    }

    public function hasPrice()
    {
        return isset($this->price);
    }

    public function clearPrice()
    {
        unset($this->price);
    }

    /**
     *价格
     *
     * Generated from protobuf field <code>optional float price = 3;</code>
     * @param float $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkFloat($var);
        $this->price = $var;

        return $this;
    }

    /**
     *简介
     *
     * Generated from protobuf field <code>optional string msg = 4;</code>
     * @return string
     */
    public function getMsg()
    {
        return isset($this->msg) ? $this->msg : '';
    }

    public function hasMsg()
    {
        return isset($this->msg);
    }

    public function clearMsg()
    {
        unset($this->msg);
    }

    /**
     *简介
     *
     * Generated from protobuf field <code>optional string msg = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->msg = $var;

        return $this;
    }

    /**
     *vip标识
     *
     * Generated from protobuf field <code>int32 mark = 5;</code>
     * @return int
     */
    public function getMark()
    {
        return $this->mark;
    }

    /**
     *vip标识
     *
     * Generated from protobuf field <code>int32 mark = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setMark($var)
    {
        GPBUtil::checkInt32($var);
        $this->mark = $var;

        return $this;
    }

    /**
     *token
     *
     * Generated from protobuf field <code>string token = 6;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     *token
     *
     * Generated from protobuf field <code>string token = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    /**
     *原价
     *
     * Generated from protobuf field <code>float original_price = 7;</code>
     * @return float
     */
    public function getOriginalPrice()
    {
        return $this->original_price;
    }

    /**
     *原价
     *
     * Generated from protobuf field <code>float original_price = 7;</code>
     * @param float $var
     * @return $this
     */
    public function setOriginalPrice($var)
    {
        GPBUtil::checkFloat($var);
        $this->original_price = $var;

        return $this;
    }

}

