<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: record.proto

namespace Interact;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *返回流水信息
 *
 * Generated from protobuf message <code>interact.RecordListResponse</code>
 */
class RecordListResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *数据总条数
     *
     * Generated from protobuf field <code>int32 total_count = 1;</code>
     */
    protected $total_count = 0;
    /**
     *订单数据
     *
     * Generated from protobuf field <code>repeated .interact.RecordInfo list = 2;</code>
     */
    private $list;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $total_count
     *          数据总条数
     *     @type array<\Interact\RecordInfo>|\Google\Protobuf\Internal\RepeatedField $list
     *          订单数据
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Record::initOnce();
        parent::__construct($data);
    }

    /**
     *数据总条数
     *
     * Generated from protobuf field <code>int32 total_count = 1;</code>
     * @return int
     */
    public function getTotalCount()
    {
        return $this->total_count;
    }

    /**
     *数据总条数
     *
     * Generated from protobuf field <code>int32 total_count = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setTotalCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->total_count = $var;

        return $this;
    }

    /**
     *订单数据
     *
     * Generated from protobuf field <code>repeated .interact.RecordInfo list = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getList()
    {
        return $this->list;
    }

    /**
     *订单数据
     *
     * Generated from protobuf field <code>repeated .interact.RecordInfo list = 2;</code>
     * @param array<\Interact\RecordInfo>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Interact\RecordInfo::class);
        $this->list = $arr;

        return $this;
    }

}

