<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: record.proto

namespace Interact;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *流水信息
 *
 * Generated from protobuf message <code>interact.RecordInfo</code>
 */
class RecordInfo extends \Google\Protobuf\Internal\Message
{
    /**
     *代理商
     *
     * Generated from protobuf field <code>string agent = 1;</code>
     */
    protected $agent = '';
    /**
     *充值帐户
     *
     * Generated from protobuf field <code>string account = 2;</code>
     */
    protected $account = '';
    /**
     *充值会员种类
     *
     * Generated from protobuf field <code>string vip = 3;</code>
     */
    protected $vip = '';
    /**
     *价格
     *
     * Generated from protobuf field <code>float price = 4;</code>
     */
    protected $price = 0.0;
    /**
     *状态
     *
     * Generated from protobuf field <code>.interact.State state = 5;</code>
     */
    protected $state = 0;
    /**
     *执行次数
     *
     * Generated from protobuf field <code>int32 exec_count = 6;</code>
     */
    protected $exec_count = 0;
    /**
     *申诉内容
     *
     * Generated from protobuf field <code>string msg = 7;</code>
     */
    protected $msg = '';
    /**
     *备注信息
     *
     * Generated from protobuf field <code>string memo = 8;</code>
     */
    protected $memo = '';
    /**
     *标识
     *
     * Generated from protobuf field <code>int32 mark = 9;</code>
     */
    protected $mark = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $agent
     *          代理商
     *     @type string $account
     *          充值帐户
     *     @type string $vip
     *          充值会员种类
     *     @type float $price
     *          价格
     *     @type int $state
     *          状态
     *     @type int $exec_count
     *          执行次数
     *     @type string $msg
     *          申诉内容
     *     @type string $memo
     *          备注信息
     *     @type int $mark
     *          标识
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Record::initOnce();
        parent::__construct($data);
    }

    /**
     *代理商
     *
     * Generated from protobuf field <code>string agent = 1;</code>
     * @return string
     */
    public function getAgent()
    {
        return $this->agent;
    }

    /**
     *代理商
     *
     * Generated from protobuf field <code>string agent = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAgent($var)
    {
        GPBUtil::checkString($var, True);
        $this->agent = $var;

        return $this;
    }

    /**
     *充值帐户
     *
     * Generated from protobuf field <code>string account = 2;</code>
     * @return string
     */
    public function getAccount()
    {
        return $this->account;
    }

    /**
     *充值帐户
     *
     * Generated from protobuf field <code>string account = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAccount($var)
    {
        GPBUtil::checkString($var, True);
        $this->account = $var;

        return $this;
    }

    /**
     *充值会员种类
     *
     * Generated from protobuf field <code>string vip = 3;</code>
     * @return string
     */
    public function getVip()
    {
        return $this->vip;
    }

    /**
     *充值会员种类
     *
     * Generated from protobuf field <code>string vip = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setVip($var)
    {
        GPBUtil::checkString($var, True);
        $this->vip = $var;

        return $this;
    }

    /**
     *价格
     *
     * Generated from protobuf field <code>float price = 4;</code>
     * @return float
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     *价格
     *
     * Generated from protobuf field <code>float price = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setPrice($var)
    {
        GPBUtil::checkFloat($var);
        $this->price = $var;

        return $this;
    }

    /**
     *状态
     *
     * Generated from protobuf field <code>.interact.State state = 5;</code>
     * @return int
     */
    public function getState()
    {
        return $this->state;
    }

    /**
     *状态
     *
     * Generated from protobuf field <code>.interact.State state = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setState($var)
    {
        GPBUtil::checkEnum($var, \Interact\State::class);
        $this->state = $var;

        return $this;
    }

    /**
     *执行次数
     *
     * Generated from protobuf field <code>int32 exec_count = 6;</code>
     * @return int
     */
    public function getExecCount()
    {
        return $this->exec_count;
    }

    /**
     *执行次数
     *
     * Generated from protobuf field <code>int32 exec_count = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setExecCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->exec_count = $var;

        return $this;
    }

    /**
     *申诉内容
     *
     * Generated from protobuf field <code>string msg = 7;</code>
     * @return string
     */
    public function getMsg()
    {
        return $this->msg;
    }

    /**
     *申诉内容
     *
     * Generated from protobuf field <code>string msg = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->msg = $var;

        return $this;
    }

    /**
     *备注信息
     *
     * Generated from protobuf field <code>string memo = 8;</code>
     * @return string
     */
    public function getMemo()
    {
        return $this->memo;
    }

    /**
     *备注信息
     *
     * Generated from protobuf field <code>string memo = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setMemo($var)
    {
        GPBUtil::checkString($var, True);
        $this->memo = $var;

        return $this;
    }

    /**
     *标识
     *
     * Generated from protobuf field <code>int32 mark = 9;</code>
     * @return int
     */
    public function getMark()
    {
        return $this->mark;
    }

    /**
     *标识
     *
     * Generated from protobuf field <code>int32 mark = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setMark($var)
    {
        GPBUtil::checkInt32($var);
        $this->mark = $var;

        return $this;
    }

}

