<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recommender.proto

namespace Interact;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *推荐人列表请求
 *
 * Generated from protobuf message <code>interact.RecommenderListRequest</code>
 */
class RecommenderListRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *token
     *
     * Generated from protobuf field <code>string token = 1;</code>
     */
    protected $token = '';
    /**
     *每页条数
     *
     * Generated from protobuf field <code>int32 amount = 2;</code>
     */
    protected $amount = 0;
    /**
     *页数
     *
     * Generated from protobuf field <code>int32 from = 3;</code>
     */
    protected $from = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $token
     *          token
     *     @type int $amount
     *          每页条数
     *     @type int $from
     *          页数
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Recommender::initOnce();
        parent::__construct($data);
    }

    /**
     *token
     *
     * Generated from protobuf field <code>string token = 1;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     *token
     *
     * Generated from protobuf field <code>string token = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    /**
     *每页条数
     *
     * Generated from protobuf field <code>int32 amount = 2;</code>
     * @return int
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     *每页条数
     *
     * Generated from protobuf field <code>int32 amount = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkInt32($var);
        $this->amount = $var;

        return $this;
    }

    /**
     *页数
     *
     * Generated from protobuf field <code>int32 from = 3;</code>
     * @return int
     */
    public function getFrom()
    {
        return $this->from;
    }

    /**
     *页数
     *
     * Generated from protobuf field <code>int32 from = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setFrom($var)
    {
        GPBUtil::checkInt32($var);
        $this->from = $var;

        return $this;
    }

}

