<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recommender.proto

namespace Interact;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *用户信息
 *
 * Generated from protobuf message <code>interact.RecommenderInfo</code>
 */
class RecommenderInfo extends \Google\Protobuf\Internal\Message
{
    /**
     *名称
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     *手机号
     *
     * Generated from protobuf field <code>string phone = 2;</code>
     */
    protected $phone = '';
    /**
     *URL
     *
     * Generated from protobuf field <code>string url = 3;</code>
     */
    protected $url = '';
    /**
     *账号
     *
     * Generated from protobuf field <code>float amount = 4;</code>
     */
    protected $amount = 0.0;
    /**
     *备注
     *
     * Generated from protobuf field <code>string memo = 5;</code>
     */
    protected $memo = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *          名称
     *     @type string $phone
     *          手机号
     *     @type string $url
     *          URL
     *     @type float $amount
     *          账号
     *     @type string $memo
     *          备注
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Recommender::initOnce();
        parent::__construct($data);
    }

    /**
     *名称
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     *名称
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     *手机号
     *
     * Generated from protobuf field <code>string phone = 2;</code>
     * @return string
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     *手机号
     *
     * Generated from protobuf field <code>string phone = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPhone($var)
    {
        GPBUtil::checkString($var, True);
        $this->phone = $var;

        return $this;
    }

    /**
     *URL
     *
     * Generated from protobuf field <code>string url = 3;</code>
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     *URL
     *
     * Generated from protobuf field <code>string url = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->url = $var;

        return $this;
    }

    /**
     *账号
     *
     * Generated from protobuf field <code>float amount = 4;</code>
     * @return float
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     *账号
     *
     * Generated from protobuf field <code>float amount = 4;</code>
     * @param float $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkFloat($var);
        $this->amount = $var;

        return $this;
    }

    /**
     *备注
     *
     * Generated from protobuf field <code>string memo = 5;</code>
     * @return string
     */
    public function getMemo()
    {
        return $this->memo;
    }

    /**
     *备注
     *
     * Generated from protobuf field <code>string memo = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setMemo($var)
    {
        GPBUtil::checkString($var, True);
        $this->memo = $var;

        return $this;
    }

}

